[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
multimap = "0.9.1"
serde = { version = "1.0.190", features = ["derive"] }
num-traits = "0.2.17"
regex = "1.10.2"
serde_regex = "1.1.0"
